Skillpoints
Wylx-Bot/Wylx pull request #105
Opened 2022-10-09 07:26 UTC by SnakeJ419

2022-10-09 23:04 UTC, 1Revenger1 requested changes

2022-10-09 23:04 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        Member member = selectionResults.event().getGuild().getMemberById(selectionResults.event().getUserId());
Break up lines
Also why do we need the user here anyway?

2022-10-09 23:04 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        Member member = selectionResults.event().getGuild().getMemberById(selectionResults.event().getUserId());
You get a member object from a reaction right? Why not pass that through instead of the ID?

2022-10-09 23:04 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        embed.addField("Stat Levels", String.format(":one: HP: %d\n:two: Speed: %d\n:three: Damage: %d\n:four: EXP Multiplier: %d\n:five: Reset Skill Points\n:x: Stop Editing",
Maybe do
```
"""
:one: HP: %d
:two: Speed: %d
"""
```

2022-10-09 23:11 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        Member member = selectionResults.event().getGuild().getMemberById(selectionResults.event().getUserId());
its not garunteed to not be null, so im verifying its not null and loading if it isnt

2022-10-09 23:16 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        Member member = selectionResults.event().getGuild().getMemberById(selectionResults.event().getUserId());
The member from the reaction event isn't guaranteed to be non null? That's weird. It'd probably be better to just pass the member anyway and cache it in a different function.

2022-10-09 23:44 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Core/Util/Helper.java
> +    public static void chooseFromListWithReactions(Message msg, User user, int numberOfOptions, Consumer<SelectionResults> reactionConsumer, boolean allowMultiple){
Yes I think that should happen, however there is more I'd like to do if that were to happen than just these options. So Ill make an issue for making this more usable but im not gonna fix it in this branch

2022-10-10 02:33 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/FightCommand.java
> +    public static final FightUserManager isFightingList = new FightUserManager();
We should really stop doing this. If it needs to be accessed by two classes, it gets put in it's own place that both can access somehow.

2022-10-10 02:34 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        Member member = selectionResults.event().getGuild().getMemberById(selectionResults.event().getUserId());
Member should be cached. It only has a note about users not being cached looking in the javadocs.

2022-10-10 17:23 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/FightCommand.java
> +    public static final FightUserManager isFightingList = new FightUserManager();
This is what singleton patterns are for ig...

2022-10-10 18:03 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/FightCommand.java
> +    public static final FightUserManager isFightingList = new FightUserManager();
yeah, not quite sure what the pattern should be here.

2022-10-13 22:28 UTC, 1Revenger1 submitted a review, later dismissed

2022-10-13 23:01 UTC, 1Revenger1 requested changes

2022-10-13 23:01 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        System.out.println(ctx.args().length);
*baps*

2022-10-13 23:01 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/SkillPointsCommand.java
> +        System.out.println(ctx.args().length);
ow

2022-10-13 23:03 UTC, 1Revenger1 approved these changes

2022-10-13 23:03 UTC, merged