Give error message in DMs on hierarchy error
Wylx-Bot/Wylx pull request #118
Opened 2023-02-01 06:50 UTC by 1Revenger1

2023-02-01 08:38 UTC, joshuabrown419 requested changes
Duplicated code probably maybe bad

2023-02-01 08:38 UTC, joshuabrown419 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
> +        }
one line if?

2023-02-01 08:38 UTC, joshuabrown419 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
>              }
Should probably also send a message to the user in the case they try to add a role that no longer exists so they know what happened

2023-02-01 08:38 UTC, joshuabrown419 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
>          }
Any reason to not move this code into a method so its not duplicated? We could just replace assign/remove with literally `assign/remove` or just `modify`

2023-02-01 08:38 UTC, joshuabrown419 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
> +                    "Please contact an admin within `" + guild.getName() + "` server to fix this."
Thought we were gonna change this to be `from` instead of `within`

2023-02-01 08:41 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
> +        }
Something wrong with this?

2023-02-01 08:43 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
> +                    "Please contact an admin within `" + guild.getName() + "` server to fix this."
Oh, you were talking about the last line? I thought you were talking about the first line, oops. Of makes way more sense there lol.

2023-02-01 08:43 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
>          }
Uhhh, I didn't think about doing that. They were next to each other so I guess it wasn't too egregious when I was writing it. I can make it a method though.

2023-02-01 08:46 UTC, joshuabrown419 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
> +        }
I mean as in make it a oneliner
`if (role == null) return;`

2023-02-01 08:47 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
> +        }
Oh. Is that a style we want? ~~MISRA standards require brackets in our embedded stuff so I e sort of formed that habit~~

2023-02-02 00:51 UTC, joshuabrown419 commented on src/main/java/com/wylxbot/wylx/Core/Processing/ReactionProcessing.java
> +        }
if you want to leave it as is its fine, looks cleaner to make it one line imo

2023-02-03 06:09 UTC, joshuabrown419 approved these changes
LGTM

2023-02-03 06:11 UTC, merged