Unified error messages among $play and $repeat
Wylx-Bot/Wylx pull request #128
Opened 2023-10-30 05:07 UTC by VVill-ga

Currently, the `play` command and `repeat` command show error messages that include `$` as a prefix. For all other commands, the `getDescription(ctx.prefix())` function is used and the set prefix is inserted into the message. This pull request brings this standardization over to the `play` and `repeat` commands.

2023-11-09 00:22 UTC, joshuabrown419 requested changes
almost good, one tiny change

2023-11-09 00:22 UTC, joshuabrown419 commented on src/main/java/com/wylxbot/wylx/Commands/ServerUtil/RepeatCommand.java
> +            event.getChannel().sendMessage(getDescription(ctx.prefix())).queue();
Can you have these combined into one message so we dont have to make two requests, rate limiting and such

2023-11-16 02:47 UTC, VVill-ga commented on src/main/java/com/wylxbot/wylx/Commands/ServerUtil/RepeatCommand.java
> +            event.getChannel().sendMessage(getDescription(ctx.prefix())).queue();
I have combined these two lines into one `getChannel().sendMessage()` which matches other commands as opposed to `getMessage().reply()`.

2023-11-21 00:17 UTC, joshuabrown419 approved these changes
LGTM

2024-04-24 05:31 UTC, merged