DB working
Wylx-Bot/Wylx pull request #72
Opened 2022-04-26 04:28 UTC by 1Revenger1

2022-04-27 17:39 UTC, SnakeJ419 requested changes
Why is there role stuff in core, I thought we had decided that core was only for modular core stuff that could be used by other command packages.

Also why such a hyper custom data structure for the role information being stored in DB, there's a very modular system already in place for discord elements. Since you're adding essentially a new data type to the DB instead of adding something to the server data structure (I am fine that it is it's own data type I think it makes sense for what you want from it) you shouldn't need to write a custom coded and can just make an extension of DiscordElement.

I haven't read the code thoroughly enough to check but does the reaction stuff reconnect at restart or is the connection to the messages lost if there's a restart?

2022-04-27 18:01 UTC, 1Revenger1 commented
Core stuff is just for stuff that can be used between commands/aren't directly to commands I thought. Music stuff for example can't be used really outside of Music commands. I don't quite get this?

I wasn't really sure how to hook up the discord elements thing. Now that I think about it, I guess it'd just be a new element with 3-4 new identifiers just for it? I also wanted to mess with custom codecs a bit more to see if I could get Mongo to decode them for us without needing to call Decode and stuff.

It retrieves the menu from the DB (or cache) if it's a message from the bot. There isn't any connection that needs to occur.

2022-04-27 18:17 UTC, SnakeJ419 commented
Core stuff is for the first part of your slash, it's part of why I wanted you to write a generic dm handler because some of the stuff reaction roles has to do because we don't have something for that is very "core" functionality. As for music the reasoning there is that there had been an intent to add in a soundboard under the ttrpg so wylxs ability to connect to and use voice is pretty core imo, whereas roles are never going to see use outside of roles.

Getting mongo to use the codecs for us, good idea and definitely a modification that should be made to the db (in a different pr), but for the roles stuff can can you convert it to a discord element so we have one set of database code we're maintaining?

Sounds good, esp since it's being cached I think that's a just fine implementation

2022-04-27 22:24 UTC, SnakeJ419 commented
Thoughts on renaming "ReactionProcessing" to something role specific and putting it elsewhere? Im ok with  not making a generic version of reaction processing... I think, but I think the name should be different, because if we start getting more reaction based listeners I would either want them to go in a different place or to generify this, not just add spaghetti code on top

2022-04-28 19:16 UTC, 1Revenger1 commented
> Thoughts on renaming "ReactionProcessing" to something role specific and putting it elsewhere? Im ok with not making a generic version of reaction processing... I think, but I think the name should be different, because if we start getting more reaction based listeners I would either want them to go in a different place or to generify this, not just add spaghetti code on top

All of our listeners are in this package, I'd rather not move it. The only other listeners are temporary ones which have short lives. If we did end up moving, we should probably move the Voice Channel one too...

2022-04-28 21:05 UTC, SnakeJ419 requested changes
We really need to sit down and define style guidelines for \*everything* threw some errors when I was trying to test the UX so those should probably be fixed lol. Please look at the comment I made in `RoleMenuIdentifiers` before you make changes to the encoder/decoder

2022-04-28 21:05 UTC, SnakeJ419 commented on src/main/java/Commands/Roles/RolesUtil/RoleMenu.java
> +
Why down here instead of above the constructor like normal for global variables?

2022-04-28 21:09 UTC, 1Revenger1 commented on src/main/java/Database/RoleMenuIdentifiers.java
> +public enum RoleMenuIdentifiers implements DiscordIdentifiers {
It was how it was originally written and I didn't want to rewrite the code/decode, lol. Plus, you generally want all the details about a menu at once, so you just grab the stuff from the database once instead of a few times to get each variable.

2022-04-28 21:09 UTC, 1Revenger1 commented on src/main/java/Database/DiscordElement.java
> +        } catch (ClassCastException e) {
If it can't cast, it throws an exception. It was just wrong before.

2022-04-28 21:10 UTC, SnakeJ419 commented on src/main/java/Database/RoleMenuIdentifiers.java
> +public enum RoleMenuIdentifiers implements DiscordIdentifiers {
yeah but im still 50% certain the document is cached anyways, and your current encode/decode seems broken anyways... Id rather it wasnt a fight with the db for control if you dont need to do something special

2022-04-28 22:42 UTC, 1Revenger1 commented on src/main/java/Commands/Roles/ModifyRoleMenuCommand.java
> +        public DMListener(RoleMenu menu, User user, Guild guild) throws ErrorResponseException {
Added 15 minute timer

2022-05-04 23:05 UTC, SnakeJ419 requested changes
Very close, only minor changes

2022-05-04 23:05 UTC, SnakeJ419 commented on src/main/java/Commands/Roles/ModifyRoleMenuCommand.java
> +            ctx.event().getMessage().reply("User private messages are blocked!").queue();
Tell the user what we need from them instead of what the problem is. Something like "Unable to send you a DM for setup, make sure you allow messages from users you share a server with"

2022-05-04 23:48 UTC, SnakeJ419 approved these changes
👍

2022-05-04 23:52 UTC, merged