82 fixdbbooboos
Wylx-Bot/Wylx pull request #84
Opened 2022-05-02 22:33 UTC by SnakeJ419

Make sure the codecs look right, ive tested them and read them twice but im still not sure and I dont want to brick the db

2022-05-03 18:38 UTC, 1Revenger1 requested changes
Not finished, just a couple of minor things.
Will look at DiscordElement later.

2022-05-03 18:38 UTC, 1Revenger1 commented on src/main/java/Core/Events/ServerEventManager.java
> +			manager.serverDB = db.getServer(id);
Save off the server and do 
```
serverDb.getSetting(ServerIde...)
manager.serverDB = serverDb;
```
Don't think you need the if statement either?

2022-05-03 22:17 UTC, SnakeJ419 commented on src/main/java/Core/Events/ServerEventManager.java
> +			manager.serverDB = db.getServer(id);
If statement is bc it only needs to be set once, figured that it was a greater average save to not save the db pointer every time than the cost of requesting it twice once per server each restart

2022-05-03 22:58 UTC, 1Revenger1 commented on src/main/java/Core/Events/ServerEventManager.java
> +			manager.serverDB = db.getServer(id);
If we're really starting to micro optimize this much.... (We don't need to btw, please don't), then branching would probably take longer.
I mostly just care about readability/making it easier to read.

2022-05-04 16:47 UTC, 1Revenger1 commented on src/main/java/Database/DiscordElement.java
> +            System.out.println("Cache Read");
Extra print

2022-05-04 16:50 UTC, 1Revenger1 commented on src/main/java/Database/DiscordElement.java
>          if (!settingDoc.get("complex", false)) {
Could we just check the return value for getCodec?
Then we wouldn't need to encode "complex" at all anymore.
Removing the check for "complex" would keep it compatible with the DB as well.

2022-05-04 16:56 UTC, 1Revenger1 commented on src/main/java/Database/DiscordElement.java
>          if (!settingDoc.get("complex", false)) {
```suggestion
        Codec<T> codec = identifier.getCodec()
        if (codec != null) {
            // Use codec here?
```

2022-05-04 18:43 UTC, 1Revenger1 requested changes

2022-05-04 18:43 UTC, 1Revenger1 commented on src/main/java/Database/DiscordElement.java
> +            data = ((Codec<T>) identifier.getCodec()).decode(reader, null);
Can use codec variable here since we know it's not null

2022-05-04 18:43 UTC, 1Revenger1 commented on src/main/java/Database/DiscordElement.java
> +        if(cachedObject != null)
Please use brackets (and add a space before the first paranthesis)

2022-05-04 18:43 UTC, 1Revenger1 commented on src/main/java/Database/DiscordElement.java
> +        if(identifier.getCodec() != null){
Don't care if you save off codec in a variable or just call getCodec both times, keep it consistent with getSetting though.

2022-05-04 18:56 UTC, 1Revenger1 approved these changes

2022-05-04 18:57 UTC, merged