timing and dsplay for various events
Wylx-Bot/Wylx pull request #91
Opened 2022-05-09 23:52 UTC by SnakeJ419

2022-05-11 17:07 UTC, 1Revenger1 requested changes

2022-05-11 17:07 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Database/Codecs/WylxStatsCodec.java
> +
Constant keys maybe? Reduce error if this ever gets edited in the future.

2022-05-11 17:35 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Database/DbElements/GlobalIdentifiers.java
> +    BotStats("Wylx_Stats", WylxStats.class, () -> new WylxStats(0, 0, 0, 0,0, 0), new WylxStatsCodec());
What formatting is wrong?

2022-05-11 17:36 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Database/DbElements/GlobalIdentifiers.java
> +    BotStats("Wylx_Stats", WylxStats.class, () -> new WylxStats(0, 0, 0, 0,0, 0), new WylxStatsCodec());
It's called bot stats bc otherwise it overlaps with the class name lol

2022-05-11 18:18 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Database/DbElements/GlobalIdentifiers.java
> +    BotStats("Wylx_Stats", WylxStats.class, () -> new WylxStats(0, 0, 0, 0,0, 0), new WylxStatsCodec());
```suggestion
    BotStats("Wylx_Stats", WylxStats.class, () -> new WylxStats(0, 0, 0, 0, 0, 0), new WylxStatsCodec());
```

2022-05-11 22:32 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Database/DbElements/GlobalIdentifiers.java
> +    GlobalIdentifiers(String identifier, Class<?> dataType, Supplier<Object> defaultSupplier){
Is this constructor still needed?

2022-05-11 22:34 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Database/DbElements/GlobalIdentifiers.java
> +    GlobalIdentifiers(String identifier, Class<?> dataType, Supplier<Object> defaultSupplier){
It's for anything in the future that gets added

2022-05-12 05:20 UTC, 1Revenger1 requested changes
RE: Last pending convo

2022-05-12 07:07 UTC, 1Revenger1 approved these changes

2022-05-12 07:12 UTC, merged