Merge DND spells into Main
Wylx-Bot/Wylx pull request #93
Opened 2022-05-12 10:34 UTC by SnakeJ419

Im sure theres going to be a multitude of comments on this given the time I wrote it at lol
uhhhhhhh early rationale for things that'll probably get questions
Threaded bc finding most similar option from the keys is kind of an expensive operation
 - Yes I think we actually need that logic, not knowing `Firebolt` is actualy `Fire Bolt` is something I expect to see a lot of from users (or at least from me lol)
 - Reason this is broken up so much is that I eventually want to let ppl make spell lists, dunno if thats useful or not or if itll even ever get done
 - Only reason to make this a complex object in the db would be for caching and the spell builder already caches bc singleton pattern, and because its not a complex object it makes copying in the csv / updating it easier for us in the future
 - the fact that we had commas in a csv was... annoying. The csv no longer has commas that arent for separation

2022-05-16 21:53 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +                    pushBack(results, i);
Could you use a heap or a better structure instead of this?

2022-05-16 21:55 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +                    pushBack(results, i);
Oh I see, it's just over the small result array. Once you've pushed back and added the one element, couldn't you just call "break" instead of setting i to 5?

2022-05-16 21:55 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +                    pushBack(results, i);
May be able to use a Linked List too? May be better for adding something in the middle of the array. Can then just remove the last element.

2022-05-16 21:57 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +                    pushBack(results, i);
> Oh I see, it's just over the small result array. Once you've pushed back and added the one element, couldn't you just call "break" instead of setting i to 5?

ngl just completely forgot break existed, I could only think of continue and that wasnt going to do what i wanted lol

2022-05-16 21:57 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +                    pushBack(results, i);
> May be able to use a Linked List too? May be better for adding something in the middle of the array. Can then just remove the last element.

ok

2022-05-19 17:53 UTC, 1Revenger1 requested changes

2022-05-19 17:53 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +    public MessageEmbed getSpellEmbed() {
Thought - make Spell a Record.

2022-05-19 17:53 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +            formattedMessage = formattedMessage.substring(0, 1021) + "...";
Is there a better way to handle this? Multiple fields for example, sending a text file, etc?

2022-05-19 17:53 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Core/Util/Helper.java
> +                msg.addReaction(numbToEmoji.get(i+1)).queue();
Can do a flat map and then queue all the changes at once.

2022-05-19 17:53 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +    public final String[] spellLists;
Never used

2022-05-19 17:53 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/SpellCommand.java
> +                        reactionEvent -> { sendSpellInfo(spellChoices[0], ctx.event().getChannel()); },
If sent index with one consumer, this could be simplified.

2022-05-19 17:53 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +        for(String key : spellMap.keySet()) {
Maybe instead of iterating twice if you get something wildly not close, just iterate once and return a list of the top 5 spells? Command can check if the top priority is close enough.

2022-05-19 18:54 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +    public MessageEmbed getSpellEmbed() {
When people can have spell lists I want them to be able to click a button and have to spell roll it's damage, and also spell does embed generation rn

2022-05-19 18:55 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +            formattedMessage = formattedMessage.substring(0, 1021) + "...";
Multiple fields you get the separation of the header between sections, multiple messages same deal of formatting coming out weird

2022-05-19 18:56 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +    public MessageEmbed getSpellEmbed() {
Spell lists would be a user thing though, wouldn't it be?
Also you can have methods in Records.

2022-05-19 18:59 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +    public Spell getSpell(String spellName) {
Yes

2022-05-19 19:03 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +        for(String key : spellMap.keySet()) {
How would you return that information? I thought about doing that but Java doesn't have any sort of vectors like python does

2022-05-19 19:17 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +        for(String key : spellMap.keySet()) {
Can just return a list/array and check the head's distance.

2022-05-19 20:43 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/SpellCommand.java
> +            spellBuilder = SpellBuilder.getInstance();
yes, creates initialization loop with Wylx

2022-05-19 20:43 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +    public MessageEmbed getSpellEmbed() {
wait whats different about records and classes then

2022-05-20 21:47 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Core/Util/Helper.java
> +                msg.addReaction(numbToEmoji.get(i+1)).queue();
Im not able to get flat mapping to work with adding reactions, errors about not being able to infer the type of action im trying to add? I think its because im trying to add an action that doesnt have anything get passed into it so it just goes idk wtf type this is?

2022-05-20 21:58 UTC, SnakeJ419 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/Spell.java
> +    public final String[] spellLists;
everything is used Im pretty sure? every variable is referened in at least one other place (that isnt the constructor)

2022-05-20 22:18 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/DND/Util/SpellBuilder.java
> +    public Spell getSpell(String spellName) {
Where does it get used?

2022-05-29 21:03 UTC, 1Revenger1 submitted a review, later dismissed

2022-05-29 22:52 UTC, 1Revenger1 approved these changes

2022-05-29 22:52 UTC, merged