Put some haha funnies in the FightMessages
Wylx-Bot/Wylx pull request #98
Opened 2022-09-03 21:49 UTC by WaterGame2023

Well we talked mentioned this in PNW Discord, so I did it

2022-09-04 03:24 UTC, 1Revenger1 requested changes

2022-09-04 03:24 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/Util/FightMessages.java
> +        "{p2} was forced to use C++ for the robot code by {p1}',
```suggestion
        "{p2} was forced to use C++ for their robot code by {p1}',
```

2022-09-04 03:24 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/Util/FightMessages.java
> +        "{p2} got knocked the Hab by {p1}",
Check Grammer here, maybe meant "knocked off the hab"?

2022-09-04 03:24 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/Util/FightMessages.java
> +        "{p2} DDoSed by {p1}',
```suggestion
        '{p1} DDoSed {p2}',
```

2022-09-04 03:24 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/Util/FightMessages.java
> +        "{p2} was told to use windows by {p1}",
```suggestion
        "{p2} was told to use Windows by {p1}",
```

2022-09-04 03:24 UTC, 1Revenger1 commented on src/main/java/com/wylxbot/wylx/Commands/Fight/Util/FightMessages.java
> +        "{p2} was forced to update windows by {p1}",
```suggestion
        "{p2} was forced to update Windows by {p1}",
```

2022-09-05 05:59 UTC, WaterGame2023 reviewed
Added the suggestions.  Thank you

2022-09-09 04:04 UTC, 1Revenger1 approved these changes

2022-09-09 04:04 UTC, merged